CREATE DATABASE ECOM12;
USE ECOM12;
DROP  TABLE USER12;
CREATE TABLE USER12(
FNAME VARCHAR(122),
LNAME VARCHAR(154),
EMAIL VARCHAR(67) PRIMARY KEY,
USERNAME VARCHAR(69),
PASSWORD VARCHAR(78)
);
TRUNCATE TABLE user12;
drop table cart12;
CREATE TABLE CART12(
PRODUCT_ID varchar(23),
PRODUCT_NAME VARCHAR(78),
PRODUCT_PRICE VARCHAR(67),
USEREMAIL VARCHAR(56),
PRODUCT_QUANTITY VARCHAR(78),
FOREIGN KEY (USEREMAIL) REFERENCES USER12(EMAIL)
);
TRUNCATE TABLE CART12;

SELECT * FROM USER12;
SELECT * FROM CART12;